include(CTest)
function(add_dz_test TEST_NAME TEST_SRC)
    add_executable(${TEST_NAME} ${TEST_SRC})
    target_include_directories(${TEST_NAME} PRIVATE ${DIRECTZ_INCLUDE_DIRS})
    target_link_libraries(${TEST_NAME} PRIVATE DirectZ)
    target_compile_features(${TEST_NAME} PRIVATE cxx_std_20)
    set_output_dir(${TEST_NAME})
    add_test(NAME ${TEST_NAME} COMMAND $<TARGET_FILE_DIR:${TEST_NAME}>/${TEST_NAME}${TEST_EXT})
endfunction()
# add_dz_test(DZ_ShaderReflect tests/ShaderReflect.cpp)
# add_dz_test(DZ_Particle2D tests/Particle2D.cpp)
# add_dz_test(DZ_AssetStream tests/AssetStream.cpp)
# add_dz_test(DZ_LineGrid tests/LineGrid.cpp)
# add_dz_test(DZ_D7Stream tests/D7Stream.cpp)
# add_dz_test(DZ_ImGuiTest tests/ImGui.cpp)
# add_dz_test(DZ_ECSTest tests/ECS.cpp)
# add_dz_test(DZ_SharedMemoryProducer tests/SharedMemoryProducer.cpp)
# add_dz_test(DZ_SharedMemoryConsumer tests/SharedMemoryConsumer.cpp)
# add_dz_test(DZ_AST tests/AST.cpp)
# add_dz_test(DZ_SO tests/SO.cpp)
add_dz_test(DZ_CMake tests/CMake.cpp)
# add_dz_test(DZ_function tests/function.cpp)
file(COPY images/Suzuho-Ueda.bmp DESTINATION ${CMAKE_BINARY_DIR}/images)
file(COPY images/hi.bmp DESTINATION ${CMAKE_BINARY_DIR}/images)
file(COPY models/SaiyanOne.glb DESTINATION ${CMAKE_BINARY_DIR}/models)
file(COPY models/GoldenSportsCar.glb DESTINATION ${CMAKE_BINARY_DIR}/models)
file(COPY models/RedSportsCar.glb DESTINATION ${CMAKE_BINARY_DIR}/models)
file(COPY models/metal_plane.glb DESTINATION ${CMAKE_BINARY_DIR}/models)
file(COPY hdri/autumn_field_puresky_4k.hdr DESTINATION ${CMAKE_BINARY_DIR}/hdri)
file(COPY hdri/zwartkops_straight_afternoon_4k.hdr DESTINATION ${CMAKE_BINARY_DIR}/hdri)