
include(GNUInstallDirs)
if(ANDROID)
    set(CMAKE_INSTALL_LIBDIR "${CMAKE_INSTALL_LIBDIR}/android/${CMAKE_SYSTEM_PROCESSOR}")
    set(CMAKE_INSTALL_BINDIR "${CMAKE_INSTALL_BINDIR}/android/${CMAKE_SYSTEM_PROCESSOR}")
endif()
message(STATUS "CMAKE_INSTALL_LIBDIR: ${CMAKE_INSTALL_LIBDIR}")
message(STATUS "CMAKE_INSTALL_BINDIR: ${CMAKE_INSTALL_BINDIR}")