name: Build Android aarch64

on:
  push:
    branches:
      - run-actions

permissions:
  contents: write

jobs:
  build-android:
    runs-on: windows-2025

    env:
      ANDROID_NDK_VERSION: 26.1.10909125
      ANDROID_API_LEVEL: 31
      ANDROID_ABI: arm64-v8a
      ANDROID_PLATFORM: android-31

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          choco install ninja openssl wget unzip
        shell: powershell

      - name: Download and Extract Android NDK
        run: |
          $url = "https://dl.google.com/android/repository/android-ndk-r27c-windows.zip"
          wget $url -OutFile "ndk.zip"
          Expand-Archive ndk.zip -DestinationPath "$env:USERPROFILE\\ndk"
          echo "ANDROID_NDK_ROOT=$env:USERPROFILE\\ndk\\android-ndk-r27c" | Out-File -Append $env:GITHUB_ENV
        shell: powershell

      - name: Configure and Build
        run: |
          cmake -B build -G Ninja `
            -DCMAKE_BUILD_TYPE=Debug `
            -DCMAKE_TOOLCHAIN_FILE=$env:ANDROID_NDK_ROOT/build/cmake/android.toolchain.cmake `
            -DANDROID_ABI=${{ env.ANDROID_ABI }} `
            -DANDROID_PLATFORM=${{ env.ANDROID_PLATFORM }}
          
          cmake --build build
        shell: powershell