name: Build iOS (arm64)

on:
  push:
    branches:
      - run-actions
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-ios:
    runs-on: macos-latest

    env:
      IOS_PLATFORM: OS64
      IOS_ARCH: arm64
      CMAKE_OSX_ARCHITECTURES: arm64
      CMAKE_OSX_SYSROOT: iphoneos
      CMAKE_IOS_INSTALL_COMBINED: ON

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          brew install ninja

      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.2
        with:
          version: 1.4.309.0
          cache: true

      - name: Set iOS Toolchain Variables
        id: toolchain
        run: |
          export SDKROOT=$(xcrun --sdk iphoneos --show-sdk-path)
          export CC=$(xcrun --sdk iphoneos -f clang)
          export CXX=$(xcrun --sdk iphoneos -f clang++)
          export AR=$(xcrun --sdk iphoneos -f ar)
          export RANLIB=$(xcrun --sdk iphoneos -f ranlib)
          export IOS_ARCH=arm64
          export CFLAGS="-isysroot $SDKROOT -arch $IOS_ARCH -mios-version-min=12.0"
          export TARGET_DIR=$(pwd)/cross-build/iphoneos.$IOS_ARCH

          echo "CC=$CC" >> "$GITHUB_ENV"
          echo "CXX=$CXX" >> "$GITHUB_ENV"
          echo "AR=$AR" >> "$GITHUB_ENV"
          echo "RANLIB=$RANLIB" >> "$GITHUB_ENV"
          echo "SDKROOT=$SDKROOT" >> "$GITHUB_ENV"
          echo "CFLAGS=$CFLAGS" >> "$GITHUB_ENV"
          echo "TARGET_DIR=$TARGET_DIR" >> "$GITHUB_ENV"
          echo "IOS_ARCH=$IOS_ARCH" >> "$GITHUB_ENV"

      - name: Build OpenSSL
        run: |
          curl -LO https://www.openssl.org/source/openssl-1.1.1w.tar.gz
          tar -xf openssl-1.1.1w.tar.gz
          cd openssl-1.1.1w

          ./Configure ios64-cross no-shared no-dso \
            --prefix=$TARGET_DIR/openssl \
            CC="$CC" \
            CPP="$CXX" \
            CFLAGS="$CFLAGS" \
            AR="$AR" \
            RANLIB="$RANLIB"

          make -j$(sysctl -n hw.logicalcpu)
          make install_sw

      - name: Configure
        run: |
          cmake -G Ninja -B build \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_OSX_ARCHITECTURES=$CMAKE_OSX_ARCHITECTURES \
            -DCMAKE_SYSTEM_NAME=iOS \
            -DCMAKE_OSX_SYSROOT=$SDKROOT \
            -DCMAKE_INSTALL_PREFIX=install \
            -DCMAKE_C_COMPILER=$CC \
            -DCMAKE_CXX_COMPILER=$CXX \
            -DCMAKE_AR=$AR \
            -DCMAKE_RANLIB=$RANLIB \
            -DVulkan_INCLUDE_DIR=$VULKAN_SDK/include \
            -DVulkan_LIBRARY=$VULKAN_SDK/lib/libMoltenVK.a \
            -DOPENSSL_ROOT_DIR=$TARGET_DIR/openssl

      - name: fix_format_security
        run: python3 fix_format_security.py build

      - name: Build
        run: cmake --build build

      - name: Install
        run: cmake --install build

      - name: Package
        run: |
          cpack --config build/CPackConfig.cmake
          ls -lah releases

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: releases
          path: releases
