name: Build Linux

on:
  push:
    branches:
      - run-actions
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: write

env:
  DIRECTZ_VERSION: "1.1.1.1"

jobs:
  configure-build-and-package-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies on Linux
        run: |
          sudo apt update
          sudo apt install nasm libvulkan-dev libssl-dev libx11-dev uuid-dev libglx-dev libgl1-mesa-dev libxfixes-dev libxrandr-dev libxkbcommon-dev libxcb-keysyms1-dev libdrm-dev ninja-build libwayland-client0 libwayland-server0 libwayland-dev libxfixes-dev libxcb-xfixes0-dev libxrender-dev libxrandr-dev libxcb-util-dev libdrm-dev libgtkmm-3.0-dev
        shell: bash

      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.2
        with:
          version: 1.4.309.0
          cache: true

      - name: Configure
        run: cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_INSTALL_PREFIX=install
        shell: bash

      - name: Build
        run: cmake --build build
        shell: bash

      - name: Install
        run: cmake --install build
        shell: bash

      - name: Package
        run: |
          cpack --config build/CPackConfig.cmake
          ls -lah releases
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DirectZ-${{ env.DIRECTZ_VERSION }}-debian-x86_64.deb
          path: DirectZ-${{ env.DIRECTZ_VERSION }}-debian-x86_64.deb