name: Build MacOS (ARM)

on:
  push:
    branches:
      - run-actions
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: write

env:
  DIRECTZ_VERSION: "1.1.1.1"

jobs:
  configure-build-and-package-macos-arm:
    runs-on: macos-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies on macOS
        run: |
          brew install nasm
        shell: bash

      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.2
        with:
          version: 1.4.309.0
          cache: true

      - name: Configure
        run: cmake -B build -D CMAKE_BUILD_TYPE=Debug -D CMAKE_C_COMPILER=clang -D CMAKE_CXX_COMPILER=clang++ -G Ninja
        shell: bash

      - name: Build
        run: cmake --build build
        shell: bash

      - name: Install
        run: sudo cmake --install build
        shell: bash

      - name: Package
        run: |
          cpack --config build/CPackConfig.cmake
          ls -lah releases
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DirectZ-${{ env.DIRECTZ_VERSION }}-darwin-arm.pkg
          path: DirectZ-${{ env.DIRECTZ_VERSION }}-darwin-arm.pkg