name: Build MacOS (ARM)

on:
  push:
    branches:
      - run-actions
      - macos-actions
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-macos-arm:
    runs-on: macos-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies on macOS
        run: |
          brew install nasm
        shell: bash

      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.2
        with:
          version: 1.4.309.0
          cache: true

      - name: Configure
        run: cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_INSTALL_PREFIX=install
        shell: bash

      - name: Build
        run: cmake --build build
        shell: bash

      - name: Install
        run: cmake --install build
        shell: bash

      - name: Package
        run: |
          cpack --config build/CPackConfig.cmake
          ls -lah releases
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: releases
          path: releases