name: Build Windows

on:
  push:
    branches:
      - run-actions
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: write

jobs:
  configure-build-and-package-windows:
    runs-on: windows-2025
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies on Windows
        run: |
          choco install dos2unix nasm
          C:\\msys64\\msys2_shell.cmd -defterm -no-start -mingw64 -here -use-full-path -c "pacman -S --noconfirm make diffutils"
        shell: bash

      - name: Install NSIS
        run: |
          curl -L -o nsis-3.11-setup.exe "https://cytranet-dal.dl.sourceforge.net/project/nsis/NSIS%203/3.11/nsis-3.11-setup.exe?viasf=1"
          ./nsis-3.11-setup.exe /S
        shell: bash

      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.2
        with:
          version: 1.4.309.0
          cache: true

      - name: Configure
        run: cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_INSTALL_PREFIX=install
        shell: cmd

      - name: Build
        run: cmake --build build
        shell: cmd

      - name: Install
        run: cmake --install build
        shell: cmd

      - name: Package
        run: |
          cpack --config build/CPackConfig.cmake
          ls -lah releases
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: releases
          path: releases